#!/usr/bin/env python3
"""
merge_llm.py — Merge LLM-enriched content back into report-data.json.

Reads llm-enriched.json (generated by LLM agent) and merges enriched
fields into report-data.json, with validation gates.

Architecture position:
    enrich_llm.py → [AGENT generates] → llm-enriched.json → **merge_llm.py** → report-data.json
                                                                                     ↓
                                                                                   render

Quality gates:
  1. hiện_trạng must contain artboard ID (4 digits)
  2. tác_động must NOT contain generic severity labels
  3. nguyên_tắc must cite a recognized heuristic
  4. references must have valid URLs from heuristic-db
  5. đề_xuất_steps must have >= 2 items (UXP only)

Usage:
    python3 merge_llm.py --module /path/to/module/
    python3 merge_llm.py --base /path/to/final/
    python3 merge_llm.py --module /path/to/module/ --dry-run
    python3 merge_llm.py --module /path/to/module/ --force   # skip quality gates
"""

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


# ═══════════════════════════════════════════════════════════════════════
# QUALITY VALIDATION
# ═══════════════════════════════════════════════════════════════════════

SEVERITY_LABELS = [
    'nghiêm trọng', 'critical', 'major', 'minor',
    'lỗi nghiêm trọng', 'gây gián đoạn',
]

KNOWN_HEURISTICS = [
    'Nielsen', 'WCAG', 'Fitts', 'Hick', 'Jakob', 'Miller',
    'Peak', 'Zeigarnik', 'Von Restorff', 'Doherty', 'Aesthetic',
]


def validate_item(item: dict, item_type: str = 'uxp') -> list[dict]:
    """Validate LLM output quality. Returns list of issues."""
    issues: list[dict] = []

    item_id = item.get('id', '?')

    # 1. hiện_trạng — must have artboard ID
    hien_trang = item.get('hiện_trạng', '')
    if hien_trang:
        if not re.search(r'\d{4}', hien_trang):
            issues.append({
                'field': 'hiện_trạng',
                'level': 'warning',
                'message': f'{item_id}: Missing artboard ID in hiện_trạng',
            })
    else:
        issues.append({
            'field': 'hiện_trạng',
            'level': 'error',
            'message': f'{item_id}: hiện_trạng is empty',
        })

    # 2. tác_động — must NOT contain severity labels
    tac_dong = item.get('tác_động', '')
    if tac_dong:
        for label in SEVERITY_LABELS:
            if label in tac_dong.lower():
                issues.append({
                    'field': 'tác_động',
                    'level': 'warning',
                    'message': f'{item_id}: tác_động contains severity label "{label}"',
                })
                break
    else:
        issues.append({
            'field': 'tác_động',
            'level': 'error',
            'message': f'{item_id}: tác_động is empty',
        })

    # 3. nguyên_tắc — must cite recognized heuristic
    nguyen_tac = item.get('nguyên_tắc', '')
    if nguyen_tac:
        if not any(h in nguyen_tac for h in KNOWN_HEURISTICS):
            issues.append({
                'field': 'nguyên_tắc',
                'level': 'warning',
                'message': f'{item_id}: No recognized heuristic cited in nguyên_tắc',
            })
    else:
        issues.append({
            'field': 'nguyên_tắc',
            'level': 'error',
            'message': f'{item_id}: nguyên_tắc is empty',
        })

    # 4. references — valid URLs
    refs = item.get('references', [])
    for ref in refs:
        url = ref.get('url', '')
        if url and not url.startswith('http'):
            issues.append({
                'field': 'references',
                'level': 'error',
                'message': f'{item_id}: Invalid URL "{url}" for ref "{ref.get("name", "?")}"',
            })
        if not ref.get('name'):
            issues.append({
                'field': 'references',
                'level': 'warning',
                'message': f'{item_id}: Reference missing name',
            })

    # 5. đề_xuất_steps — UXP only, >= 2 steps
    if item_type == 'uxp':
        steps = item.get('đề_xuất_steps', [])
        if isinstance(steps, list) and len(steps) < 2:
            issues.append({
                'field': 'đề_xuất_steps',
                'level': 'warning',
                'message': f'{item_id}: Only {len(steps)} proposal steps (need >= 2)',
            })

    return issues


# ═══════════════════════════════════════════════════════════════════════
# MERGE ENGINE
# ═══════════════════════════════════════════════════════════════════════

def _merge_uxp(uxp: dict, enriched: dict) -> list[str]:
    """Merge enriched fields into a UXP record. Returns list of updated fields."""
    updated = []

    # user_impact ← tác_động
    if enriched.get('tác_động'):
        uxp['user_impact'] = enriched['tác_động']
        updated.append('user_impact')

    # heuristic ← nguyên_tắc
    if enriched.get('nguyên_tắc'):
        uxp['heuristic'] = enriched['nguyên_tắc']
        updated.append('heuristic')

    # description_rich ← hiện_trạng (new field, template can optionally use)
    if enriched.get('hiện_trạng'):
        uxp['hiện_trạng'] = enriched['hiện_trạng']
        updated.append('hiện_trạng')

    # solution_steps ← đề_xuất_steps
    if enriched.get('đề_xuất_steps'):
        steps = enriched['đề_xuất_steps']
        if isinstance(steps, list) and steps:
            uxp['solution_steps'] = steps
            updated.append('solution_steps')

    # references ← references
    if enriched.get('references'):
        refs = enriched['references']
        if isinstance(refs, list):
            # Merge: keep existing, add new (deduplicate by name)
            existing_names = {r.get('name', '') for r in uxp.get('references', [])}
            merged_refs = list(uxp.get('references', []))
            for ref in refs:
                if ref.get('name') and ref['name'] not in existing_names:
                    merged_refs.append(ref)
                    existing_names.add(ref['name'])
            uxp['references'] = merged_refs
            uxp['ref_count'] = len(merged_refs) + (1 if uxp.get('ddl_ref') else 0)
            updated.append('references')

    # Mark as LLM-enriched
    if updated:
        uxp['_enriched_by'] = 'llm'

    return updated


def _merge_gap(gap: dict, enriched: dict, screen_id: str) -> list[str]:
    """Merge enriched fields into a Gap record. Returns list of updated fields."""
    updated = []

    if enriched.get('tác_động'):
        gap['user_impact'] = enriched['tác_động']
        updated.append('user_impact')

    if enriched.get('nguyên_tắc'):
        gap['heuristic'] = enriched['nguyên_tắc']
        updated.append('heuristic')

    if enriched.get('hiện_trạng'):
        gap['description'] = enriched['hiện_trạng']
        gap['hiện_trạng'] = enriched['hiện_trạng']
        updated.append('description')

    if enriched.get('references'):
        refs = enriched['references']
        if isinstance(refs, list):
            existing_names = {r.get('name', '') for r in gap.get('references', [])}
            merged_refs = list(gap.get('references', []))
            for ref in refs:
                if ref.get('name') and ref['name'] not in existing_names:
                    merged_refs.append(ref)
                    existing_names.add(ref['name'])
            gap['references'] = merged_refs
            gap['ref_count'] = len(merged_refs) + (1 if gap.get('ddl_evidence') or gap.get('ref') else 0)
            updated.append('references')

    if updated:
        gap['_enriched_by'] = 'llm'

    return updated


def merge_module(module_dir: Path, dry_run: bool = False,
                 force: bool = False) -> dict:
    """Merge llm-enriched.json into report-data.json for one module."""
    module_dir = module_dir.resolve()
    enriched_path = module_dir / 'llm-enriched.json'
    report_path = module_dir / 'report-data.json'

    result = {
        'module': module_dir.name,
        'status': 'ok',
        'uxp_merged': 0,
        'gap_merged': 0,
        'fields_updated': 0,
        'quality_issues': [],
    }

    if not enriched_path.exists():
        result['status'] = 'skip'
        result['reason'] = 'no llm-enriched.json'
        return result

    if not report_path.exists():
        result['status'] = 'error'
        result['reason'] = 'no report-data.json'
        return result

    enriched_data = json.loads(enriched_path.read_text(encoding='utf-8'))
    report_data = json.loads(report_path.read_text(encoding='utf-8'))

    # Build lookup from enriched data
    enriched_items = enriched_data if isinstance(enriched_data, list) else enriched_data.get('items', [])
    enriched_by_id: dict[str, dict] = {}
    for item in enriched_items:
        item_id = item.get('id', '')
        if item_id:
            enriched_by_id[item_id] = item

    # Validate all items first
    all_issues: list[dict] = []
    for item in enriched_items:
        item_id = item.get('id', '')
        item_type = 'uxp' if item_id.startswith('UXP') else 'gap'
        issues = validate_item(item, item_type)
        all_issues.extend(issues)

    result['quality_issues'] = all_issues
    errors = [i for i in all_issues if i['level'] == 'error']
    warnings = [i for i in all_issues if i['level'] == 'warning']

    if errors and not force:
        result['status'] = 'blocked'
        result['reason'] = f'{len(errors)} quality errors (use --force to override)'
        return result

    # Merge UXPs
    for uxp in report_data.get('uxps', []):
        uxp_id = uxp.get('id', '')
        enriched = enriched_by_id.get(uxp_id)
        if not enriched:
            continue

        updated = _merge_uxp(uxp, enriched)
        if updated:
            result['uxp_merged'] += 1
            result['fields_updated'] += len(updated)

    # Merge Gaps
    for sg in report_data.get('gaps_by_screen', []):
        screen_id = sg.get('screen_id', '')
        for gap in sg.get('gaps', []):
            gap_num = gap.get('num', '')
            gap_id = f"Gap#{gap_num}@{screen_id}"
            enriched = enriched_by_id.get(gap_id)
            if not enriched:
                # Try alternate ID format
                gap_id_alt = f"Gap#{gap_num}"
                enriched = enriched_by_id.get(gap_id_alt)
            if not enriched:
                continue

            updated = _merge_gap(gap, enriched, screen_id)
            if updated:
                result['gap_merged'] += 1
                result['fields_updated'] += len(updated)

    # Write back
    if not dry_run and (result['uxp_merged'] > 0 or result['gap_merged'] > 0):
        report_path.write_text(
            json.dumps(report_data, ensure_ascii=False, indent=2) + '\n',
            encoding='utf-8',
        )

    return result


# ═══════════════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════════════

def print_report(result: dict):
    """Print merge report."""
    module = result['module']
    status = result['status']

    if status == 'skip':
        print(f'  ⏭️  {module}: {result.get("reason", "skipped")}')
        return
    if status == 'error':
        print(f'  ❌ {module}: {result.get("reason", "error")}')
        return
    if status == 'blocked':
        print(f'  🚫 {module}: {result.get("reason", "blocked")}')
        issues = result.get('quality_issues', [])
        for issue in issues:
            if issue['level'] == 'error':
                print(f'      ❌ {issue["message"]}')
        return

    uxp_m = result['uxp_merged']
    gap_m = result['gap_merged']
    fields = result['fields_updated']
    issues = result.get('quality_issues', [])
    warnings = [i for i in issues if i['level'] == 'warning']

    print(f'  ✅ {module}: {uxp_m} UXPs + {gap_m} Gaps merged '
          f'({fields} fields updated)')

    if warnings:
        print(f'      ⚠️  {len(warnings)} warnings:')
        for w in warnings[:5]:
            print(f'         {w["message"]}')
        if len(warnings) > 5:
            print(f'         ... +{len(warnings) - 5} more')


def main():
    parser = argparse.ArgumentParser(
        description='Merge LLM-enriched content into report-data.json'
    )
    parser.add_argument('--module', type=Path,
                        help='Path to single module directory')
    parser.add_argument('--base', type=Path,
                        help='Base directory to find all modules')
    parser.add_argument('--dry-run', action='store_true',
                        help='Preview changes without writing')
    parser.add_argument('--force', action='store_true',
                        help='Skip quality gate errors')
    args = parser.parse_args()

    modules: list[Path] = []
    if args.module:
        modules = [args.module.resolve()]
    elif args.base:
        import os
        base = args.base.resolve()
        for root, dirs, files in os.walk(base):
            if 'llm-enriched.json' in files:
                modules.append(Path(root))
        modules.sort()
    else:
        parser.error('Specify either --module or --base')

    if not modules:
        print('No modules with llm-enriched.json found.', file=sys.stderr)
        sys.exit(1)

    mode = '🔍 DRY RUN' if args.dry_run else ('⚡ FORCE' if args.force else '🔀 MERGING')
    print(f'\n{"═" * 60}')
    print(f'  {mode} — {len(modules)} module(s)')
    print(f'{"═" * 60}\n')

    total_fields = 0
    for mod_dir in modules:
        result = merge_module(mod_dir, dry_run=args.dry_run, force=args.force)
        print_report(result)
        total_fields += result.get('fields_updated', 0)

    if len(modules) > 1:
        print(f'\n{"─" * 60}')
        print(f'  📊 BATCH: {total_fields} fields merged across {len(modules)} modules')
    print()


if __name__ == '__main__':
    main()
